// <auto-generated />
using System;
using BackEnd.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackEnd.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackEnd.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckIn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CheckOut")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BackEnd.Entities.HotelRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomTypeId");

                    b.ToTable("HotelRooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 100m,
                            RoomNumber = "101",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Price = 100m,
                            RoomNumber = "102",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 3,
                            Price = 100m,
                            RoomNumber = "103",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 4,
                            Price = 100m,
                            RoomNumber = "104",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 5,
                            Price = 100m,
                            RoomNumber = "105",
                            RoomTypeId = 1
                        },
                        new
                        {
                            Id = 6,
                            Price = 150m,
                            RoomNumber = "201",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Price = 150m,
                            RoomNumber = "202",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 8,
                            Price = 150m,
                            RoomNumber = "203",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 9,
                            Price = 150m,
                            RoomNumber = "204",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 10,
                            Price = 150m,
                            RoomNumber = "205",
                            RoomTypeId = 2
                        },
                        new
                        {
                            Id = 11,
                            Price = 250m,
                            RoomNumber = "301",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 12,
                            Price = 250m,
                            RoomNumber = "302",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 13,
                            Price = 250m,
                            RoomNumber = "303",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 14,
                            Price = 250m,
                            RoomNumber = "304",
                            RoomTypeId = 3
                        },
                        new
                        {
                            Id = 15,
                            Price = 250m,
                            RoomNumber = "305",
                            RoomTypeId = 3
                        });
                });

            modelBuilder.Entity("BackEnd.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("BackEnd.Entities.RoomType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoomTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "One person room",
                            Name = "Single"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Two person room",
                            Name = "Double"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Premium suite",
                            Name = "Suite"
                        });
                });

            modelBuilder.Entity("BackEnd.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "alice@example.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEFakeHashAlice==",
                            Username = "alice"
                        },
                        new
                        {
                            Id = 2,
                            Email = "bob@example.com",
                            PasswordHash = "AQAAAAEAACcQAAAAEFakeHashBob==",
                            Username = "bob"
                        });
                });

            modelBuilder.Entity("BackEnd.Entities.Booking", b =>
                {
                    b.HasOne("BackEnd.Entities.HotelRoom", "HotelRoom")
                        .WithMany("Bookings")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HotelRoom");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEnd.Entities.HotelRoom", b =>
                {
                    b.HasOne("BackEnd.Entities.RoomType", "RoomTypes")
                        .WithMany("HotelRooms")
                        .HasForeignKey("RoomTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RoomTypes");
                });

            modelBuilder.Entity("BackEnd.Entities.Payment", b =>
                {
                    b.HasOne("BackEnd.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BackEnd.Entities.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BackEnd.Entities.Booking", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BackEnd.Entities.HotelRoom", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("BackEnd.Entities.RoomType", b =>
                {
                    b.Navigation("HotelRooms");
                });

            modelBuilder.Entity("BackEnd.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
